// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef DialogBreakpoint_h
#define DialogBreakpoint_h
#include <FL/Fl.H>
#if 1
#include <stdint.h>
#endif
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>

class DialogBreakpoints {
  uint8_t* bp_table = 0; 
public:
  DialogBreakpoints();
  Fl_Double_Window *windowDialog;
private:
  Fl_Input *textAddress;
  Fl_Check_Button *checkPc;
  Fl_Check_Button *checkRead;
  Fl_Check_Button *checkWrite;
  Fl_Input *textNote;
  Fl_Button *buttonCreate;
  Fl_Button *buttonRemove;
  Fl_Check_Button *checkVdpcontrol;
  Fl_Check_Button *checkPsgwrite;
  Fl_Check_Button *checkVdpread;
  Fl_Check_Button *checkVdpwrite;
public:
  void set_breakpoint_table(uint8_t* p);
};
#endif
