// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef DialogBreakpoint_h
#define DialogBreakpoint_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>

class DialogBreakpoints {
public:
  DialogBreakpoints();
  Fl_Double_Window *windowDialog;
  Fl_Browser *browserBreakpoins;
  Fl_Input *textAddress;
  Fl_Check_Button *checkPc;
  Fl_Check_Button *checkRead;
  Fl_Check_Button *checkWrite;
  Fl_Input *textNote;
  Fl_Button *buttonCreate;
  Fl_Button *buttonRemove;
};
#endif
