// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "DialogBreakpoint.h"

/**
   Dialog constructor
*/
DialogBreakpoints::DialogBreakpoints() {
  { windowDialog = new Fl_Double_Window(351, 456);
    windowDialog->user_data((void*)(this));
    { browserBreakpoins = new Fl_Browser(25, 25, 315, 340, "Breakpoints");
      browserBreakpoins->textfont(13);
      browserBreakpoins->align(Fl_Align(FL_ALIGN_TOP));
      Fl_Group::current()->resizable(browserBreakpoins);
    } // Fl_Browser* browserBreakpoins
    { textAddress = new Fl_Input(80, 370, 80, 25, "Address");
      textAddress->textfont(13);
    } // Fl_Input* textAddress
    { checkPc = new Fl_Check_Button(190, 370, 25, 25, "PC");
      checkPc->down_box(FL_DOWN_BOX);
      checkPc->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Check_Button* checkPc
    { checkRead = new Fl_Check_Button(250, 370, 25, 25, "Read");
      checkRead->down_box(FL_DOWN_BOX);
      checkRead->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Check_Button* checkRead
    { checkWrite = new Fl_Check_Button(310, 370, 25, 25, "Write");
      checkWrite->down_box(FL_DOWN_BOX);
      checkWrite->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Check_Button* checkWrite
    { textNote = new Fl_Input(80, 395, 260, 25, "Note");
      textNote->textfont(13);
    } // Fl_Input* textNote
    { buttonCreate = new Fl_Button(25, 425, 80, 25, "Create");
    } // Fl_Button* buttonCreate
    { buttonRemove = new Fl_Button(105, 425, 80, 25, "Remove");
    } // Fl_Button* buttonRemove
    windowDialog->end();
  } // Fl_Double_Window* windowDialog
}
